name: Quarto Preview

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - '_quarto.yml'
      - '.github/workflows/preview.yml'
      - '.github/workflows/publish.yml'
      - '*.qmd'
      - 'static/**'
      - 'styles.css'

concurrency: preview-${{ github.ref }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        if: github.event.action != 'closed' # skip the build if the PR has been closed
        run: |
          quarto render
          # Copy additional resources
          cp .nojekyll docs/
          mkdir -p docs/files/CV
          cp static/files/CV/Morrison_CV.pdf docs/files/CV/

      - name: List files
        shell: bash
        run: |
          echo "contents of docs/:"
          ls -la docs/
          
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@main
        with:
          source-dir: docs/
